apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service-deployment
  labels:
    app: policy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
        - name: policy-service
          image: docker.io/redfox197/policy-service-jvm:1.0
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: postgres-url
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-configmap
                  key: kafka-url
---
apiVersion: v1
kind: Service
metadata:
  name: policy-service-service
spec:
  selector:
    app: policy-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080